version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: phoenix_app
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "mix deps.get --force && mix ecto.migrate && mix phx.server"]

volumes:
  postgres_data:
